<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), 'Common.props'))\Common.props" />
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<Description>Helper package for querying NuGet feeds for intellisense in project files</Description>
		<Authors>Microsoft</Authors>
		<ProjectUrl>https://github.com/dotnet/projfiletools</ProjectUrl>
		<LicenseUrl>https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm</LicenseUrl>
		<ImageUrl>http://go.microsoft.com/fwlink/?LinkID=288859</ImageUrl>
		<Company>Microsoft</Company>
		<Copyright>Copyright © Microsoft Corporation</Copyright>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
	</ItemGroup>
	<Target Name="BuiltProjectOutputGroup" />
	<Target Name="BuiltProjectOutputGroupDependencies" />
	<Target Name="GetCopyToOutputDirectoryItems" />
	<Target Name="SatelliteDllsProjectOutputGroup" />
	<Target Name="DebugSymbolsProjectOutputGroup" />
</Project>