<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <NonShipping>true</NonShipping>
  </PropertyGroup>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), 'Common.props'))\Common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="[4.18.4]" />
    <PackageReference Include="FluentAssertions" Version="7.2.0" />
    <PackageReference Include="NuGet.Frameworks" Version="7.0.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ProjectFileTools.NuGetSearch\ProjectFileTools.NuGetSearch.csproj" />
  </ItemGroup>
</Project>